# Generated by Django 5.0.2 on 2025-02-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Cost',
            new_name='cost',
        ),
    ]
